/*
 * this module tries to do a lot of dirty work of analyzing spatial data and moving things and then
 * also setting flags for more sophisticated modules.
 */

#include "globals.h"

#include "game_manipulation.h"
#include "common_logic.h"
#include "ball_physics.h"
#include "collision.h"
#include "vector_math.h"
#include "geometry.h"
#include "base_logic.h"
#include "rules_strikes.h"
#include "base_control.h"
#include "rules_pure/player_utils.h"

#define EVALUATION_CONSTANT_IN_AIR 200.0f
#define EVALUATION_CONSTANT_AFTER_HIT_ONCE 5.0f
#define CATCH_DISTANCE 2.6f

#define BALL_FINAL_POINT_APPROXIMATION_CONSTANT 45.0f
#define BALL_DROP_TO_FINAL_POINT_APPROXIMATION_CONSTANT 20.0f
#define BALL_DROP_TARGET_CONSTANT 8.0f
#define BALL_DROP_EVAL_CONSTANT 40.0f
#define BALL_ON_GROUND_SLOW_FACTOR 0.98f
#define BALL_SLOW_FACTOR_X 0.8f
#define BALL_SLOW_FACTOR_Z 0.8f
#define BALL_SLOW_FACTOR_Y 0.55f
#define BALL_BOUNCE_THRESHOLD 0.02f
#define PLAYER_TOO_CLOSE_TO_CATCH_LIMIT 15.0f

static void update_ball_to_player(MatchSession* match);
static void update_ball_status(MatchSession* match, GameFlowState* gameFlowState);
static void
check_if_ball_can_be_caught(MatchSession* match, const FieldPositions* field_positions, int* play_sound_effect);
static void player_location_orientation_and_targets(MatchSession* match, const FieldPositions* field_positions);
static void basemen_replacements(MatchSession* match);
static void check_if_near_home_location(MatchSession* match);
static void base_runner_movements_on_base_arrivals(MatchSession* match, const RefereeState* referee);
static void move_idling_players_to_home_location(MatchSession* match);
static void rank_players_and_move_them(MatchSession* match);
static void update_models(MatchSession* match);
static void
update_ball_home_status(MatchSession* match, const FieldPositions* field_positions, const RefereeState* referee);

void game_manipulation(
    MatchSession* match, const FieldPositions* field_positions, const RefereeState* referee, int* play_sound_effect
)
{
    update_ball_status(match, &(match->gameFlowState)); // update ball's location due to velocity, also update ball's
                                                        // velocity due to gravity, and set some flags related to ball
    check_if_ball_can_be_caught(match, field_positions, play_sound_effect);
    check_if_near_home_location(match);
    basemen_replacements(match);
    move_idling_players_to_home_location(match);
    rank_players_and_move_them(
        match
    ); // ranks players and moves them when needed. its ranked lists are also used for changing players.
    player_location_orientation_and_targets(
        match, field_positions
    ); // update every players' location and orientation according to player's velocity and ball's location.
    base_runner_movements_on_base_arrivals(
        match, referee
    ); // Process arrival events generated by location update immediately
    update_ball_to_player(
        match
    ); // if some player has the ball, update ball velocity so that the ball will follow the player
    update_ball_home_status(match, field_positions, referee); // NEW: Check if ball is at home
    update_models(match);
}

void init_game_manipulation(GameFlowState* gameFlowState)
{
    gameFlowState->closeToGround = 0;
}

static void update_ball_status(MatchSession* match, GameFlowState* gameFlowState)
{
    if (match->ballInfo.lastLastLocationUpdate == 1) {
        vec3_set_from_vector(&(match->ballInfo.lastLocation), &(match->ballInfo.location));
        match->ballInfo.lastLastLocationUpdate = 0;
    }
    // check first if ball's moving flag is 1, so that no overhead of doing updates on nothing.
    if (match->ballInfo.moving == 1) {
        // update lastLocation and location.
        vec3_set_from_vector(&(match->ballInfo.lastLocation), &(match->ballInfo.location));
        physics_apply_velocity(&(match->ballInfo.location), &(match->ballInfo.velocity));
        if (match->pII.hasBallIndex == -1) {
            // if ball is free then we make sure that it stays within the play area.
            if (physics_resolve_field_boundaries(
                    &(match->ballInfo.location), &(match->ballInfo.velocity), FIELD_FRONT, FIELD_BACK, FIELD_LEFT,
                    FIELD_RIGHT, BALL_SLOW_FACTOR_Y
                )) {
                // if ball hit a wall, we need to refresh AI targets because the prediction is now wrong
                match->pRAI.refresh_catch_and_change = 1;
            }
            if (match->ballInfo.onGround == 0) {
                // if ball is not on the ground yet, let it be affected by gravity.
                physics_apply_gravity(&(match->ballInfo.velocity), 1.0f);
                // if ball now comes close to the ground
                if (physics_check_ground_collision(match->ballInfo.location.y, BALL_SIZE / 2)) {
                    // we check out of bounds situation only if we are close to ground to avoid
                    // unnecesaary overhead
                    if (gameFlowState->closeToGround == 0) {
                        gameFlowState->closeToGround = 1;
                    }
                    // it could be its first time
                    if (match->ballInfo.currentFlightHasHitGround ==
                        0) { // to avoid situation where it feels like player changing key doesnt work
                        // because if this wasnt here, rankedindicesarrayindex would be always initialized to 0 with
                        // every change.
                        match->ballInfo.currentFlightHasHitGround = 1;
                        match->gameEvents.ballHitGround = 1;
                        // this is used to track if ball has been dropped after a catch to avoid wounding
                        match->ballInfo.hitsGroundToUnWound = 1;
                    }
                    // Strike/Ball counting logic moved to Referee_Update (referee.c)
                    // Pitch state reset moved to consolidation (game_consolidation.c)

                    // if ball has enough y-velocity it will bounce
                    if (match->ballInfo.velocity.y < -BALL_BOUNCE_THRESHOLD) {
                        // so try to update ranks of fielders
                        match->pRAI.refresh_catch_and_change = 1;
                        // change the direction of y-velocity
                        match->ballInfo.velocity.y = -match->ballInfo.velocity.y;
                        vec3_set_xyz(
                            &(match->ballInfo.velocity), BALL_SLOW_FACTOR_X * match->ballInfo.velocity.x,
                            BALL_SLOW_FACTOR_Y * match->ballInfo.velocity.y,
                            BALL_SLOW_FACTOR_Z * match->ballInfo.velocity.z
                        );

                    }
                    // if instead we dont have enough y-velocity to bounce, we just set velocity to 0, location to
                    // ground and change ranked indices for the last time.
                    else if (match->ballInfo.velocity.y < 0) {
                        match->ballInfo.onGround = 1;
                        match->pRAI.refresh_catch_and_change = 1;
                        match->ballInfo.location.y = BALL_SIZE / 2;
                        match->ballInfo.velocity.y = 0.0f;
                    }
                } else {
                    if (gameFlowState->closeToGround == 1) {
                        gameFlowState->closeToGround = 0;
                    }
                }

            } else {
                // if we are rolling on the ground already, slow down the velocity a bit and stop ball if x and z
                // -velocities are small enough
                vec3_set_xz(
                    &(match->ballInfo.velocity), BALL_ON_GROUND_SLOW_FACTOR * match->ballInfo.velocity.x,
                    BALL_ON_GROUND_SLOW_FACTOR * match->ballInfo.velocity.z
                );
                if (vec3_is_small_enough_circle_xz_v(&(match->ballInfo.velocity), 0.01f)) {
                    match->ballInfo.moving = 0;
                    match->ballInfo.lastLastLocationUpdate = 1;
                    vec3_set_xyz(&(match->ballInfo.velocity), 0.0f, 0.0f, 0.0f);
                }
            }
        }
    }
}

static void update_ball_to_player(MatchSession* match)
{
    if (match->pII.hasBallIndex != -1) {
        // if someone has ball and that someone is moving and ball movement needs updating, give it same v as the player
        // has
        if (match->playerInfo[match->pII.hasBallIndex].cPI.moving == 1) {
            if (match->ballInfo.needsMoveUpdate == 1) {
                match->ballInfo.moving = 1;
                match->ballInfo.needsMoveUpdate = 0;
                vec3_set_xyz(
                    &(match->ballInfo.velocity), match->playerInfo[match->pII.hasBallIndex].tPI.velocity.x, 0.0f,
                    match->playerInfo[match->pII.hasBallIndex].tPI.velocity.z
                );
            }
        }
        // if someone has ball and that someone doesn't move but ball still moves, stop the ball
        else {
            if (match->ballInfo.moving == 1) {
                match->ballInfo.moving = 0;
                match->ballInfo.lastLastLocationUpdate = 1;
                vec3_set_xyz(&(match->ballInfo.velocity), 0.0f, 0.0f, 0.0f);
            }
        }
    }
}

// so the goal is check if ball is close enough to any of the players and if so, do all the work needed
// to move game to post-catch state.
static void
check_if_ball_can_be_caught(MatchSession* match, const FieldPositions* field_positions, int* play_sound_effect)
{
    int i;
    // so to go to do checking we should first confirm that it even is possible by checking that no one has ball
    // and pitch is not going on. also cant catch if it just happens to be frame of updating ranks
    // as that could make some weird things happen. try on the next frame again.
    if (match->pII.hasBallIndex == -1 && match->pRAI.pitch_state == PITCH_STAGE_NONE &&
        match->pRAI.refresh_catch_and_change != 1) {
        for (i = PLAYERS_IN_TEAM + JOKER_COUNT; i < PLAYERS_IN_TEAM * 2 + JOKER_COUNT; i++) {
            // so we confirm that this particular player is valid to catch, by checking his lastHadBallIndex.
            // its purpose is to deny players catching balls right after throwing them.
            // but if ball has hit ground, we dont care about lastHadBallIndex anymore.
            // allow players to drop balls and catch if thrown close to them by themselves.
            if ((i != match->pII.lastHadBallIndex || match->ballInfo.currentFlightHasHitGround == 1)) {
                Vector3D distance;
                float limit = CATCH_DISTANCE;
                distance.x = match->playerInfo[i].tPI.location.x - match->ballInfo.location.x;
                distance.z = match->playerInfo[i].tPI.location.z - match->ballInfo.location.z;
                distance.y = 2 * match->playerInfo[i].tPI.location.y / 5 - match->ballInfo.location.y;
                // check if ball is close enough to this particular player.
                if (vec3_is_small_enough_sphere(&distance, limit) == 1) {
                    // weird things would happen
                    int j;
                    int baseCatcherFlag = 0;
                    float p1x, p2x, p1z, p2z;
                    if (match->pII.lastHadBallIndex != -1) {
                        p1x = match->playerInfo[i].tPI.location.x;
                        p1z = match->playerInfo[i].tPI.location.z;
                        p2x = match->playerInfo[match->pII.lastHadBallIndex].tPI.location.x;
                        p2z = match->playerInfo[match->pII.lastHadBallIndex].tPI.location.z;
                        if (match->pRAI.throw_going_to_base != -1 &&
                            (i == match->pII.catcherOnBaseIndex[match->pRAI.throw_going_to_base] ||
                             i == match->pII.catcherReplacerOnBaseIndex[match->pRAI.throw_going_to_base])) {
                            baseCatcherFlag = 1;
                        }
                    }
                    // to avoid annyoing twitching we need to check that catching player is far enough
                    if (match->pII.lastHadBallIndex == -1 || match->ballInfo.currentFlightHasHitGround == 1 ||
                        baseCatcherFlag == 1 ||
                        !vec3_is_small_enough_circle_xz(p1x - p2x, p1z - p2z, PLAYER_TOO_CLOSE_TO_CATCH_LIMIT)) {
                        // ensure that player that previously was controlled doesnt continue his key-controlled movement
                        // when key is still down when control changes. note this could be different player than the one
                        // who caught the ball.
                        if (match->pII.controlIndex != -1 &&
                            match->playerInfo[match->pII.controlIndex].cPI.moving == 1) {
                            stop_movement(match->playerInfo, match->pII.controlIndex);
                        }
                        // if throwRecoil is 1, model will be automatically set to 0 when animation ends
                        // but if its 0, we must change it from having ball to not having ball.
                        if (match->pII.controlIndex != -1 &&
                            match->playerInfo[match->pII.controlIndex].cTPI.throwRecoil == 0) {
                            match->playerInfo[match->pII.controlIndex].cPI.model = PLAYER_ANIM_STAND_NO_BALL;
                        }
                        // set busyCatching to 0 for every one who was busy if ball is caught so that
                        // players are free to be moved to their home locations.
                        for (j = PLAYERS_IN_TEAM + JOKER_COUNT; j < PLAYERS_IN_TEAM * 2 + JOKER_COUNT; j++) {
                            if (match->playerInfo[j].cTPI.busyCatching == 1) {
                                match->playerInfo[j].cTPI.busyCatching = 0;
                                // also stop them so that decisions about moving to home location can be made.
                                stop_movement(match->playerInfo, j);
                            }
                        }
                        // stop the guy who caught the ball
                        stop_movement(match->playerInfo, i);
                        // but start moving again if movement key being held at the same time. for smooth movement.
                        smooth_out_movement(match);
                        // set the has ball model.
                        match->playerInfo[i].cPI.model = PLAYER_ANIM_STAND_WITH_BALL;

                        // Emit catch event (referee will evaluate if it's a wounding catch)
                        match->gameEvents.catchMade = 1;

                        // make sound
                        *play_sound_effect = SOUND_CATCH;
                        match->pRAI.throw_going_to_base = -1;
                        match->pII.controlIndex = i;
                        match->pII.hasBallIndex = i;

                        // and set running flag
                        match->playerInfo[match->pII.controlIndex].cPI.running = 1;
                        // stop the ball and hide it. if player starts to move again,
                        // then ball's velocity will also be updated agian.
                        match->ballInfo.visible = 0;
                        match->ballInfo.moving = 0;
                        match->ballInfo.onGround = 0;
                        match->ballInfo.currentFlightHasHitGround = 0;
                        // and set ball's location to player's location (X, Z), but use proper held height (Y)
                        vec3_set_from_vector(&(match->ballInfo.location), &(match->playerInfo[i].tPI.location));
                        match->ballInfo.location.y = BALL_HEIGHT_WITH_PLAYER;
                    }
                }
            }
        }
    }
}
// when moving fielders automatically, we often use the knowledge of whether we are near home location or not
// so here we check if we thats the case
static void check_if_near_home_location(MatchSession* match)
{
    int i;
    for (i = PLAYERS_IN_TEAM + JOKER_COUNT; i < PLAYERS_IN_TEAM * 2 + JOKER_COUNT; i++) {
        // we check it only for moving players to reduce overhead a bit.
        if (match->playerInfo[i].cPI.moving == 1) {

            float dx = match->playerInfo[i].tPI.location.x - match->playerInfo[i].tPI.homeLocation.x;
            float dz = match->playerInfo[i].tPI.location.z - match->playerInfo[i].tPI.homeLocation.z;
            // if we are already close, we check if happen to have gone out.
            if (match->playerInfo[i].cTPI.isNearHomeLocation == 1) {
                if (vec3_is_small_enough_circle_xz(dx, dz, DISTANCE_FROM_HOME_LOCATION_THRESHOLD) == 0) {
                    match->playerInfo[i].cTPI.isNearHomeLocation = 0;
                }
            }
            // if are out we check if happened to wander in.
            else if (match->playerInfo[i].cTPI.isNearHomeLocation == 0) {
                if (vec3_is_small_enough_circle_xz(dx, dz, DISTANCE_FROM_HOME_LOCATION_THRESHOLD) == 1) {
                    match->playerInfo[i].cTPI.isNearHomeLocation = 1;
                }
            }
        }
    }
}
static void base_runner_movements_on_base_arrivals(MatchSession* match, const RefereeState* referee)
{
    // so everything starts with some player arriving base, this flag is set on target checking function.
    if (match->gameEvents.playerArrivedAtBase == 1) {
        int i;
        // we check every player who is a baserunner ( or batter )
        for (i = 0; i < PLAYERS_IN_TEAM + JOKER_COUNT; i++) {
            int index = i;
            // check if this particular player was one who arrived. there can be many though so we cant break out after
            // this.
            if (match->playerInfo[index].bTPI.baseId != BASE_NONE && match->playerRuntime[index].arrivedToBase == 1) {

                // no need to check on this player anymore when next runner arrives and this one has stayed where he
                // was.
                match->playerRuntime[index].arrivedToBase = 0;
                // if out has been made, player is removed immediately from the game so we wouldnt be here.
                // if wound has been made, player still tries to get to next base, so we have to handle that here.
                if (match->playerInfo[index].bTPI.state != PLAYER_STATE_OUT) {
                    int j;
                    // so after we have a valid player, we are going to check to which base he arrived
                    // and after that do the actions corresponding to base and direction.
                    // we dont have the code handling batter arriving homebase here as
                    // it didn't need much of a work, so its handled in target checking function.
                    // homeruns are checked here though, in that case base==4? so its out of this loop.
                    for (j = 1; j < BASE_COUNT; j++) {
                        if (base_to_int_index(match->playerInfo[index].bTPI.baseId) == j) {
                            // arrived to base
                            // if we were taking a free walk, we stop it now, BUT only if we aren't wounded/out
                            if (match->playerInfo[index].bTPI.state == PLAYER_STATE_ADVANCING_FREELY &&
                                match->playerInfo[index].bTPI.state != PLAYER_STATE_WOUNDED &&
                                match->playerInfo[index].bTPI.state != PLAYER_STATE_OUT) {
                                match->playerInfo[index].bTPI.state =
                                    PLAYER_STATE_ON_BASE; // Transition out of ADVANCING_FREELY
                            }
                        }
                    }
                    // whether we got safely to first base or were wounded, we have to set batterIndex to -1
                    // so that next player can go batting.
                    // if (match->pII.batterIndex == index) match->pII.batterIndex = -1;
                    // if the player arrived to a base and had it marked as 4, it means that it possibly a run.
                    if (match->playerInfo[index].bTPI.baseId == BASE_HOME_SCORED) {
                        // if we were safe at base 3, we are not anymore.
                        if (get_base_controller(match, referee, BASE_THIRD) == index) {
                        }
                        // We rely on Referee to adjudicate the run via is_regular_run.
                        // No need for pre-checks or manual removal here; reconcile will handle it.
                    }
                }
            }
        }
        // set the flag off as now everything has been handled.
        // match->gameEvents.playerArrivedAtBase = 0; // Handled by clear_frame_events
    }
}

static void basemen_replacements(MatchSession* match)
{
    int i;
    for (i = 0; i < BASE_COUNT; i++) {
        // if player is not in his home base
        if (match->playerInfo[match->pII.catcherOnBaseIndex[i]].cTPI.isNearHomeLocation == 0) {
            // start moving replacer there instead if he is not moving already or if player does not control him
            if (match->pII.catcherReplacerOnBaseIndex[i] != match->pII.controlIndex) {
                if (match->playerInfo[match->pII.catcherReplacerOnBaseIndex[i]].cTPI.replacingStage ==
                    REPLACEMENT_IDLE) {
                    move_to_target(
                        match->playerInfo, match->pII.catcherReplacerOnBaseIndex[i],
                        &(match->playerInfo[match->pII.catcherOnBaseIndex[i]].tPI.homeLocation)
                    );

                    match->playerInfo[match->pII.catcherReplacerOnBaseIndex[i]].cTPI.replacingStage =
                        REPLACEMENT_ACTIVE;
                    match->playerInfo[match->pII.catcherReplacerOnBaseIndex[i]].cTPI.replacingBase = (BaseID)i;
                    // can go replacing even if was busy catching before.
                    match->playerInfo[match->pII.catcherReplacerOnBaseIndex[i]].cTPI.busyCatching = 0;
                }
            }
        }
        // if player is on his base
        else if (match->playerInfo[match->pII.catcherOnBaseIndex[i]].cTPI.isNearHomeLocation == 1) {
            // and there's someone there or going there, move him back ( if player doesnt control )
            if (match->pII.catcherReplacerOnBaseIndex[i] != match->pII.controlIndex) {
                if (match->playerInfo[match->pII.catcherReplacerOnBaseIndex[i]].cTPI.replacingStage !=
                    REPLACEMENT_IDLE) {
                    if (match->playerInfo[match->pII.catcherReplacerOnBaseIndex[i]].cTPI.replacingBase == (BaseID)i) {
                        move_to_target(
                            match->playerInfo, match->pII.catcherReplacerOnBaseIndex[i],
                            &(match->playerInfo[match->pII.catcherReplacerOnBaseIndex[i]].tPI.homeLocation)
                        );

                        match->playerInfo[match->pII.catcherReplacerOnBaseIndex[i]].cTPI.replacingStage =
                            REPLACEMENT_IDLE;
                        match->playerInfo[match->pII.catcherReplacerOnBaseIndex[i]].cTPI.replacingBase = BASE_NONE;
                    }
                }
            }
        }
    }
}

static void move_idling_players_to_home_location(MatchSession* match)
{
    int i;
    // if not catching ball or replacing or in home location, move to home location.
    for (i = PLAYERS_IN_TEAM + JOKER_COUNT; i < PLAYERS_IN_TEAM * 2 + JOKER_COUNT; i++) {
        if (match->playerInfo[i].cPI.moving == 0) {
            if (i != match->pII.controlIndex) {
                if (match->playerInfo[i].cTPI.isNearHomeLocation == 0) {
                    if (match->playerInfo[i].cTPI.replacingStage == REPLACEMENT_IDLE) {
                        if (match->playerInfo[i].cTPI.busyCatching == 0) {
                            move_to_target(match->playerInfo, i, &(match->playerInfo[i].tPI.homeLocation));
                        }
                    }
                }
            }
        }
    }
}

static void rank_players_and_move_them(MatchSession* match)
{
    // calculating these things only makes sense when no one has ball. even though these usually should be mutually
    // exclusive theres a small change that refreshCatchAndchange == 1 and ball has been caught.
    // refresh_catch_and_change is set 1 when ball is thrown or bat or dropped but also when ball hits ground for the
    // first time and when it stops and also when player is changed. there could be more.
    if (match->pRAI.refresh_catch_and_change == 1 && match->pII.hasBallIndex == -1) {

        int i, j;
        int rankedIndices[RANKED_FIELDERS_COUNT];
        float rankedEvals[RANKED_FIELDERS_COUNT];
        float v = match->ballInfo.velocity.y;
        float a = -GRAVITY;
        float s = 0.0f;
        float ballDropX; // where the ball will land
        float ballDropZ;
        float evalBallX; // place that we use to calculate player rankings
        float evalBallZ;
        float dirX; // ball's velocity's direction
        float dirZ;
        float time; // used to calculate ballDrop. framecount it takes from ball to land after movement's start ( like
                    // in throwin or batting )
        float dot;
        float speed;
        float distance;
        float evaluation;
        if (match->ballInfo.currentFlightHasHitGround == 0) {
            if (match->pRAI.throw_going_to_base == -1) {
                s = 1.1f; // when batting the height is something like this
            } else {
                s = BALL_HEIGHT_WITH_PLAYER;
            }
        } else {
            s = 0;
        }
        // initialize rankedIndices and rankedEvals
        for (i = 0; i < RANKED_FIELDERS_COUNT; i++) {
            rankedIndices[i] = 0;
            rankedEvals[i] = 500.0f; // infinity
        }
        // calculate how long it takes for ball come back down from heights
        time = (float)(-v - sqrt(v * v - 2 * a * s)) / a;
        // ballDropX is the point where ball will approximately land after the air time
        ballDropX = match->ballInfo.location.x + time * match->ballInfo.velocity.x;
        ballDropZ = match->ballInfo.location.z + time * match->ballInfo.velocity.z;

        dirX = match->ballInfo.velocity.x;
        dirZ = match->ballInfo.velocity.z;
        speed = (float)sqrt(dirX * dirX + dirZ * dirZ);
        if (speed < EPSILON) speed = 0.1f;
        dirX = dirX / speed;
        dirZ = dirZ / speed;

        // here some approximations for situations when ball is still in air and when ball has hit the ground.
        // targetpoint is the place where we will move the catchers and what we will use for ranking the fielders.
        if (match->ballInfo.currentFlightHasHitGround == 0) {
            float finalPointXApprox = ballDropX + match->ballInfo.velocity.x * BALL_FINAL_POINT_APPROXIMATION_CONSTANT;
            float finalPointZApprox = ballDropZ + match->ballInfo.velocity.z * BALL_FINAL_POINT_APPROXIMATION_CONSTANT;
            float multiplier = speed / (time * 0.01f);
            if (multiplier < 0.35f)
                multiplier = 0.0f;
            else if (multiplier > 0.6f)
                multiplier = 0.6f;
            else
                multiplier = (multiplier - 0.35f) * 0.6f / 0.25f;

            match->cameraState.targetPoint.x = (1 - multiplier) * ballDropX + multiplier * finalPointXApprox;
            match->cameraState.targetPoint.z = (1 - multiplier) * ballDropZ + multiplier * finalPointZApprox;

            evalBallX = ballDropX + match->ballInfo.velocity.x * BALL_DROP_EVAL_CONSTANT * 0.25f / (time * 0.01f);
            evalBallZ = ballDropZ + match->ballInfo.velocity.z * BALL_DROP_EVAL_CONSTANT * 0.25f / (time * 0.01f);
        } else if (match->ballInfo.currentFlightHasHitGround == 1 && match->ballInfo.onGround == 0) {
            match->cameraState.targetPoint.x =
                ballDropX + match->ballInfo.velocity.x * BALL_DROP_TO_FINAL_POINT_APPROXIMATION_CONSTANT;
            match->cameraState.targetPoint.z =
                ballDropZ + match->ballInfo.velocity.z * BALL_DROP_TO_FINAL_POINT_APPROXIMATION_CONSTANT;

            evalBallX = match->cameraState.targetPoint.x;
            evalBallZ = match->cameraState.targetPoint.z;
        } else {
            match->cameraState.targetPoint.x =
                ballDropX + match->ballInfo.velocity.x * BALL_FINAL_POINT_APPROXIMATION_CONSTANT;
            match->cameraState.targetPoint.z =
                ballDropZ + match->ballInfo.velocity.z * BALL_FINAL_POINT_APPROXIMATION_CONSTANT;

            evalBallX = match->cameraState.targetPoint.x;
            evalBallZ = match->cameraState.targetPoint.z;
        }

        // check only catching team players
        for (i = PLAYERS_IN_TEAM + JOKER_COUNT; i < PLAYERS_IN_TEAM * 2 + JOKER_COUNT; i++) {
            float dx; // vector from ball drop to player
            float dz;
            float distance2;
            dx = match->playerInfo[i].tPI.location.x - evalBallX;
            dz = match->playerInfo[i].tPI.location.z - evalBallZ;
            distance = (float)sqrt(dx * dx + dz * dz);
            if (distance < EPSILON) distance = 1.0f;
            dx = match->playerInfo[i].tPI.location.x - match->ballInfo.location.x;
            dz = match->playerInfo[i].tPI.location.z - match->ballInfo.location.z;
            distance2 = (float)sqrt(dx * dx + dz * dz);
            if (distance2 < EPSILON) distance2 = 1.0f;
            dx = dx / distance2;
            dz = dz / distance2;
            dot = (dx * dirX + dz * dirZ) * (dx * dirX + dz * dirZ);
            if (match->ballInfo.currentFlightHasHitGround == 0) {
                evaluation = distance - dot * EVALUATION_CONSTANT_IN_AIR * speed * speed;
            } else if (match->ballInfo.currentFlightHasHitGround == 1 && match->ballInfo.onGround == 0) {
                evaluation = distance - dot * EVALUATION_CONSTANT_AFTER_HIT_ONCE;
            } else {
                evaluation = distance;
            }
            // and then we create a array of 5 of these players ranked on their evaluation number
            for (j = 0; j < RANKED_FIELDERS_COUNT; j++) {
                if (evaluation < rankedEvals[j]) {
                    int k;
                    for (k = 4; k > j; k--) {
                        rankedEvals[k] = rankedEvals[k - 1];
                        rankedIndices[k] = rankedIndices[k - 1];
                    }
                    rankedEvals[j] = evaluation;
                    rankedIndices[j] = i;
                    break;
                }
            }
        }
        // so now we have ranked indices -array
        for (j = 0; j < RANKED_FIELDERS_COUNT; j++) {
            match->pII.fielderRankedIndices[j] = rankedIndices[j];
        }

        // then change cursor to best choice of players if flags says so
        // set for example when ball is first bat/thrown etc or when change player key is pressed.
        if (match->pRAI.init_player_selection == 1) {
            match->pII.changePlayerArrayIndex = 0;
            change_player(match);
            match->pRAI.init_player_selection = 0;
        } else {
            match->pII.changePlayerArrayIndex = -1;
        }

        // move these critical players to ball's final position
        move_ranked_to_catch(match);
    }
    match->pRAI.refresh_catch_and_change = 0;
}

static void player_location_orientation_and_targets(MatchSession* match, const FieldPositions* field_positions)
{
    int i;
    int activeBatterIndex = get_active_batter_index(match);

    for (i = 0; i < PLAYERS_IN_TEAM * 2 + JOKER_COUNT; i++) {
        // orientation updated only if ball or player moving
        if (match->ballInfo.moving == 1 || match->playerInfo[i].cPI.moving == 1) {
            if (i != match->pII.hasBallIndex) {
                if (match->playerInfo[i].cPI.running == 0) {
                    if (i != activeBatterIndex) {
                        set_orientation(match->playerInfo, &(match->ballInfo), i);
                    }
                }
            }
        }
    }
    // move players
    for (i = 0; i < PLAYERS_IN_TEAM * 2 + JOKER_COUNT; i++) {
        // players only moved if moving-flag is set to 1.
        if (match->playerInfo[i].cPI.moving == 1) {
            vec3_set_xz(
                &match->playerInfo[i].tPI.lastLocation, match->playerInfo[i].tPI.location.x,
                match->playerInfo[i].tPI.location.z
            );
            // if we are pressing against the fences, fence wont give up. we need to tell that to ball also.
            // this can happen only for fielders.
            if (i >= PLAYERS_IN_TEAM + JOKER_COUNT) {
                if ((match->playerInfo[i].tPI.location.z > FIELD_FRONT - FENCE_OFFSET &&
                     match->playerInfo[i].tPI.velocity.z > 0) ||
                    (match->playerInfo[i].tPI.location.z < FIELD_BACK + FENCE_OFFSET &&
                     match->playerInfo[i].tPI.velocity.z < 0)) {
                    match->ballInfo.needsMoveUpdate = 1;
                    match->playerInfo[i].tPI.velocity.z = 0.0f;
                }
                if ((match->playerInfo[i].tPI.location.x > FIELD_RIGHT - FENCE_OFFSET &&
                     match->playerInfo[i].tPI.velocity.x > 0) ||
                    (match->playerInfo[i].tPI.location.x < FIELD_LEFT + FENCE_OFFSET &&
                     match->playerInfo[i].tPI.velocity.x < 0)) {
                    match->playerInfo[i].tPI.velocity.x = 0.0f;
                    match->ballInfo.needsMoveUpdate = 1;
                }
            }
            // update the location by player's current velocity.
            vec3_add_xz(
                &match->playerInfo[i].tPI.location, match->playerInfo[i].tPI.velocity.x,
                match->playerInfo[i].tPI.velocity.z
            );

            // DEBUG for Wounded Players
            if (match->playerInfo[i].bTPI.state == PLAYER_STATE_WOUNDED) {
                // printf("[DEBUG] Player %d WOUNDED Moving. Pos: (%.2f, %.2f) Vel: (%.2f, %.2f) Target: (%.2f,
                // %.2f)\n", i, match->playerInfo[i].tPI.location.x,
                // match->playerInfo[i].tPI.location.z, match->playerInfo[i].tPI.velocity.x,
                // match->playerInfo[i].tPI.velocity.z, match->playerInfo[i].tPI.targetLocation.x,
                // match->playerInfo[i].tPI.targetLocation.z);
            }

            // a lot of movement in the game is handled by these se called targets. we set target location and
            // looksToTarget flag for a player and he will move to that direction with constant velocity until he
            // reaches the target. reaching is decided here. but first step to optimize this process is to have this
            // looksForTarget flag so that we can distinct between user moved players and automatically moved players.
            if (match->playerInfo[i].cPI.looksForTarget == 1) {
                // so here we now check if we happened to be close enough to our target so that we could wrap this
                // journey up.
                float dx = match->playerInfo[i].tPI.location.x - match->playerInfo[i].tPI.targetLocation.x;
                float dz = match->playerInfo[i].tPI.location.z - match->playerInfo[i].tPI.targetLocation.z;
                if (vec3_is_small_enough_circle_xz(dx, dz, TARGET_ACHIEVED_THRESHOLD) == 1) {
                    int needToStop = 1;
                    if (i == activeBatterIndex && match->playerRuntime[i].goingForward == 0) {
                        prepare_batter(match);
                    } else {
                        // select correct model for catchers.
                        if (i >= PLAYERS_IN_TEAM + JOKER_COUNT) {
                            match->playerInfo[i].cPI.model = PLAYER_ANIM_STAND_NO_BALL;
                        } else {
                            match->playerInfo[i].cPI.model = PLAYER_ANIM_STAND_BARE;
                        }
                    }
                    // if no out is made of this player ( batting team player )
                    if (i < PLAYERS_IN_TEAM + JOKER_COUNT) {
                        // so if we are moving out of the field after being wounded or tagged.
                        // here we first move to a some point outside the limits of game area
                        // and then back to a point in homebase, and then to own place on the circle.
                        // check for running because otherwise we players who were wounded before arriving a base
                        // would be stuck there standing.
                        if ((match->playerInfo[i].bTPI.state == PLAYER_STATE_OUT) ||
                            (match->playerInfo[i].bTPI.state == PLAYER_STATE_SCORED) ||
                            (match->playerInfo[i].bTPI.state == PLAYER_STATE_WOUNDED &&
                             match->playerInfo[i].cPI.running == 0)) {
                            Vector3D target;
                            if (match->playerRuntime[i].passedPathPoint == 0) {
                                match->playerRuntime[i].passedPathPoint = 1;
                                target.x = field_positions->pitchPlate.x;
                                target.z = field_positions->pitchPlate.z + HOME_RADIUS;
                            } else if (match->playerRuntime[i].passedPathPoint == 1) {
                                match->playerRuntime[i].passedPathPoint = 2;
                                target.x = match->playerInfo[i].tPI.homeLocation.x;
                                target.z = match->playerInfo[i].tPI.homeLocation.z;
                            } else {
                                stop_target_looking_player(match->playerInfo, match->playerRuntime, i);
                                set_orientation(match->playerInfo, &(match->ballInfo), i);
                                continue;
                            }
                            // and move to target
                            move_to_target(match->playerInfo, i, &target);
                            continue;
                        }
                        // if we are legally running bases
                        else {
                            // if we are at homebase, first base or second base and not leading
                            if (base_can_advance(match->playerInfo[i].bTPI.baseId) &&
                                match->playerInfo[i].bTPI.state != PLAYER_STATE_LEADING) {
                                // and moving forward
                                if (match->playerRuntime[i].goingForward == 1) {
                                    // set going forward flag to 0 as we are stopped now
                                    match->playerRuntime[i].goingForward = 0;
                                    // set new base-value and isOnBase-vaule to 1.
                                    match->playerInfo[i].bTPI.baseId = base_get_next(match->playerInfo[i].bTPI.baseId);

                                    if (match->playerInfo[i].bTPI.state != PLAYER_STATE_WOUNDED &&
                                        match->playerInfo[i].bTPI.state != PLAYER_STATE_OUT) {
                                        match->playerInfo[i].bTPI.state = PLAYER_STATE_ON_BASE;
                                    } else {
                                    }
                                    // also these are needed to do continued calculations only when needed.
                                    match->gameEvents.playerArrivedAtBase = 1;
                                    match->playerRuntime[i].arrivedToBase = 1;

                                } else {
                                    if (match->playerInfo[i].bTPI.state != PLAYER_STATE_WOUNDED &&
                                        match->playerInfo[i].bTPI.state != PLAYER_STATE_OUT &&
                                        match->playerInfo[i].bTPI.state != PLAYER_STATE_AT_BAT) {
                                        match->playerInfo[i].bTPI.state = PLAYER_STATE_ON_BASE;
                                    }
                                }
                            }
                            // so if we are on base 3
                            else if (match->playerInfo[i].bTPI.baseId == BASE_THIRD) {
                                if (match->playerRuntime[i].goingForward == 1) {
                                    // if we are moving forward and have not passed the flag yet, change the direction
                                    if (match->playerRuntime[i].passedPathPoint == 0) {
                                        match->playerRuntime[i].passedPathPoint = 1;
                                        run_to_next_base(match, field_positions, i, BASE_THIRD);
                                        needToStop = 0;
                                    }
                                    // if have passed the flag we are at homebase, so set the base to 4
                                    // and move player to its circle.
                                    else if (match->playerRuntime[i].passedPathPoint == 1) {
                                        Vector3D target;
                                        match->playerRuntime[i].passedPathPoint = 2;

                                        match->playerInfo[i].bTPI.baseId = BASE_HOME_SCORED;
                                        if (match->playerInfo[i].bTPI.state != PLAYER_STATE_WOUNDED &&
                                            match->playerInfo[i].bTPI.state != PLAYER_STATE_OUT) {
                                            match->playerInfo[i].bTPI.state = PLAYER_STATE_ON_BASE;
                                        }
                                        match->playerRuntime[i].goingForward = 0;
                                        match->gameEvents.playerArrivedAtBase = 1;
                                        match->playerRuntime[i].arrivedToBase = 1;
                                        target.x = match->playerInfo[i].tPI.homeLocation.x;
                                        target.z = match->playerInfo[i].tPI.homeLocation.z;
                                        move_to_target(match->playerInfo, i, &target);
                                        needToStop = 0;
                                    }
                                } else {
                                    // if we are coming back and have passed the point, change direction
                                    if (match->playerRuntime[i].passedPathPoint == 1) {
                                        match->playerRuntime[i].passedPathPoint = 0;
                                        run_to_previous_base(match, field_positions, i, BASE_THIRD);
                                        needToStop = 0;
                                    } else {
                                        // otherwise we are at the third base

                                        if (match->playerInfo[i].bTPI.state != PLAYER_STATE_WOUNDED &&
                                            match->playerInfo[i].bTPI.state != PLAYER_STATE_OUT) {
                                            match->playerInfo[i].bTPI.state = PLAYER_STATE_ON_BASE;
                                        }
                                        stop_target_looking_player(match->playerInfo, match->playerRuntime, i);
                                        needToStop = 0;
                                    }
                                }
                            }
                        }
                    }
                    // if procedures higher didnt handle stopping themselves
                    // we stop the player here.
                    if (needToStop == 1) {
                        stop_target_looking_player(match->playerInfo, match->playerRuntime, i);
                        set_orientation(match->playerInfo, &(match->ballInfo), i);
                    }
                }
            }
        }
        // if we dont move, it could be that we just stopped, so lets see if we should update our lastLocation.
        if (match->playerInfo[i].cPI.lastLastLocationUpdate == 1) {
            vec3_set_xz(
                &match->playerInfo[i].tPI.lastLocation, match->playerInfo[i].tPI.location.x,
                match->playerInfo[i].tPI.location.z
            );
            match->playerInfo[i].cPI.lastLastLocationUpdate = 0;
        }
    }
}
// so for animations we need to change mesh after certain intervals.
static void update_models(MatchSession* match)
{
    int i;
    // every player has some animations.
    for (i = 0; i < PLAYERS_IN_TEAM * 2 + JOKER_COUNT; i++) {
        switch (match->playerInfo[i].cPI.model) {
        case PLAYER_ANIM_WALK_NO_BALL:
        case PLAYER_ANIM_WALK_WITH_BALL:
        case PLAYER_ANIM_RUN_NO_BALL:
        case PLAYER_ANIM_RUN_WITH_BALL:
            // so first animations for walking and running. they are loops, the stage will be in range of 0 to
            // count*freq. reason this seemingly complicated way of doing this is just to provide possibility to have
            // animations with same meshcounts to have animations of different speeds.
            match->playerInfo[i].cPI.animationStage =
                (match->playerInfo[i].cPI.animationStage + 1) %
                (match->playerInfo[i].cPI.animationFrequency * match->playerInfo[i].cPI.animationStageCount);
            break;
        case PLAYER_ANIM_PITCH_WINDUP:
        case PLAYER_ANIM_PITCH_THROW:
            // throwing animations are not loops and they must end when the last stage is encountered.
            // (PLAYER_ANIM_THROW_WINDUP is no longer advanced here — its gather arc is driven directly by
            // the engine windup clock, ThrowActualization.timer, on the render side; timing dictates
            // animation. This retires the last throw animationStage writer for the windup.)
            if (match->playerInfo[i].cPI.animationStage !=
                match->playerInfo[i].cPI.animationStageCount * match->playerInfo[i].cPI.animationFrequency - 1) {
                match->playerInfo[i].cPI.animationStage = (match->playerInfo[i].cPI.animationStage + 1);
            }
            break;
        case PLAYER_ANIM_THROW_RELEASE:
            // here we do the same thing but set recoil to 0 after animation so that player can start moving and stuff
            // again.
            if (match->playerInfo[i].cPI.animationStage !=
                match->playerInfo[i].cPI.animationStageCount * match->playerInfo[i].cPI.animationFrequency - 1) {
                match->playerInfo[i].cPI.animationStage = (match->playerInfo[i].cPI.animationStage + 1);
            } else {
                match->playerInfo[i].cTPI.throwRecoil = 0;
                match->playerInfo[i].cPI.model = PLAYER_ANIM_STAND_NO_BALL;
            }
            break;
        case PLAYER_ANIM_WALK_BARE:
        case PLAYER_ANIM_RUN_BARE:
            // running and walking animations for batting team
            match->playerInfo[i].cPI.animationStage =
                (match->playerInfo[i].cPI.animationStage + 1) %
                (match->playerInfo[i].cPI.animationFrequency * match->playerInfo[i].cPI.animationStageCount);
            break;
        case PLAYER_ANIM_BAT_SWING_1:
        case PLAYER_ANIM_BAT_SWING_2:
        case PLAYER_ANIM_BAT_SWING_3:
            // batting animations are not loops, so theyll end after finishing. swinging, bunting, and spreading hands.
            if (match->playerInfo[i].cPI.animationStage !=
                match->playerInfo[i].cPI.animationStageCount * match->playerInfo[i].cPI.animationFrequency - 1) {
                match->playerInfo[i].cPI.animationStage = (match->playerInfo[i].cPI.animationStage + 1);
            }
            break;
        case PLAYER_ANIM_STAND_NO_BALL:
        case PLAYER_ANIM_STAND_WITH_BALL:
        case PLAYER_ANIM_STAND_BARE:
        case PLAYER_ANIM_BATTER_READY:
        default:
            break;
        }
    }
}

static void
update_ball_home_status(MatchSession* match, const FieldPositions* field_positions, const RefereeState* referee)
{
    int ballAtBase = get_ball_at_base_index(match, field_positions);
    if (ballAtBase == 0) {
        match->gameFlowState.ballHome = 1;

        // Camera logic from checkForOuts
        if (match->gameFlowState.homeRunCameraCounter == -1 && match->cameraState.homeRunCameraFlag == 1 &&
            (get_base_controller(match, referee, BASE_THIRD) == -1 ||
             match->playerInfo[get_base_controller(match, referee, BASE_THIRD)].bTPI.state == PLAYER_STATE_ON_BASE)) {
            match->gameFlowState.homeRunCameraCounter = 0;
        }
    } else {
        match->gameFlowState.ballHome = 0;
    }
}
